### ISSUE TITLE
Error: Module version mismatch. Expected 43, got 48

### ISSUE THREAD

**Issue by devqualwebs** [byteball/obyte-gui-wallet#284]
Hi, On running nw, On selecting user program is terminated with following error. I am using ubuntu14.04 as operating system.

```
[23263:0108/193855:INFO:CONSOLE(28501)] ""Module version mismatch. Expected 43, got 48." "undefined"", source: file:///home/qualwebs/Documents/byteball/public/angular.js (28501)

[23263:0108/193855:INFO:CONSOLE(7784)] ""stack" "Error: Module version mismatch. Expected 43, got 48.\n    at Error (native)\n    at Module.load (module.js:346:32)\n    at Function.Module._load (module.js:301:12)\n    at Module.require (module.js:356:17)\n    at require (module.js:375:17)\n    at Object.\u003Canonymous\u003E (/home/qualwebs/Documents/byteball/node_modules/sqlite3/lib/sqlite3.js:4:15)\n    at Module._compile (module.js:451:26)\n    at Object.Module._extensions..js (module.js:469:10)\n    at Module.load (module.js:346:32)\n    at Function.Module._load (module.js:301:12)"", source: file:///home/qualwebs/Documents/byteball/public/byteball.js (7784)

[23263:0108/193855:INFO:CONSOLE(3429)] ""uncaughtException"", source: file:///home/qualwebs/Documents/byteball/public/byteball.js (3429)

[23263:0108/193855:INFO:CONSOLE(7784)] ""stack" "/home/qualwebs/Documents/byteball/node_modules/byteballcore/network.js:2210\n\t\t\tfunction version2int(version){\n\t\t\t^^^^^^^^\nSyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.\n    at exports.runInThisContext (vm.js:53:16)\n    at Module._compile (module.js:434:25)\n    at Object.Module._extensions..js (module.js:469:10)\n    at Module.load (module.js:346:32)\n    at Function.Module._load (module.js:301:12)\n    at Module.require (module.js:356:17)\n    at require (module.js:375:17)\n    at window.require (\u003Canonymous\u003E:4:17)\n    at sendBugReport (file:///home/qualwebs/Documents/byteball/public/byteball.js:7737:23)\n    at EventEmitter.\u003Canonymous\u003E (file:///home/qualwebs/Documents/byteball/public/byteball.js:7785:9)"", source: file:///home/qualwebs/Documents/byteball/public/byteball.js (7784)

/home/qualwebs/Documents/byteball/node_modules/byteballcore/network.js:2210
			function version2int(version){
			^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:434:25)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at sendBugReport (file:///home/qualwebs/Documents/byteball/public/byteball.js:7737:23)
    at EventEmitter.<anonymous> (file:///home/qualwebs/Documents/byteball/public/byteball.js:7785:9)

====================
bye!
```

**Comment by tonyofbyteball** [comment]
Looks like your versions of node.js and nwjs do not match.  Please follow the instructions to the letter.
